name: square_in_app_payments
description: An open source Flutter plugin for calling Square’s native In-App Payments SDK to take in-app payments on iOS and Android.
version: 2.0.0
homepage: https://github.com/square/in-app-payments-flutter-plugin
documentation: https://github.com/square/in-app-payments-flutter-plugin

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.12.6
  flutter:
    sdk: flutter
  meta: ^1.18.0

dev_dependencies:
  build: ^4.0.7
  build_runner: ^2.15.1
  built_value_generator: ^8.12.6
  source_gen: ^4.2.3

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: sqip.flutter
        pluginClass: SquareInAppPaymentsFlutterPlugin
      ios:
        pluginClass: SquareInAppPaymentsFlutterPlugin
